from __future__ import annotations

import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "examples" / "mvp1-district" / "reference-district.pmtiles"

# A valid 1x1 transparent PNG used only as a bounded offline presentation tile.
PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
    "0000000d49444154789c6360606060000000050001a5f645400000000049454e44"
    "ae426082"
)


def _varint(value: int) -> bytes:
    result = bytearray()
    while value > 127:
        result.append((value & 127) | 128)
        value >>= 7
    result.append(value)
    return bytes(result)


def build_archive() -> bytes:
    # One z=0 tile: entry count, tile-id delta, run length, byte length, offset+1.
    root_directory = b"".join(_varint(value) for value in (1, 0, 1, len(PNG), 1))
    metadata = json.dumps(
        {
            "name": "AWG synthetic reference district",
            "description": "Presentation-only tile; authoritative topology is reference-district.osm.",
            "attribution": "Generated by the AWG project; no external geographic data.",
            "format": "png",
            "type": "overlay",
            "version": "1",
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode()

    root_offset = 127
    metadata_offset = root_offset + len(root_directory)
    tile_offset = metadata_offset + len(metadata)
    header = bytearray(127)
    header[:7] = b"PMTiles"
    header[7] = 3
    struct.pack_into(
        "<11Q",
        header,
        8,
        root_offset,
        len(root_directory),
        metadata_offset,
        len(metadata),
        tile_offset,
        0,
        tile_offset,
        len(PNG),
        1,
        1,
        1,
    )
    # clustered, internal compression, tile compression, tile type, min/max zoom
    struct.pack_into("<6B", header, 96, 1, 1, 1, 2, 0, 0)
    struct.pack_into(
        "<4iB2i",
        header,
        102,
        int(-2.2480 * 10_000_000),
        int(53.4790 * 10_000_000),
        int(-2.2330 * 10_000_000),
        int(53.4880 * 10_000_000),
        0,
        int(-2.2405 * 10_000_000),
        int(53.4835 * 10_000_000),
    )
    return bytes(header) + root_directory + metadata + PNG


def main() -> None:
    OUTPUT.write_bytes(build_archive())
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
